### ISSUE TITLE
Error: Could not find or load main class JESstartup

### ISSUE THREAD

**Issue by xiaoleihuang** [gatech-csl/jes#99]
My java runtime is Oracle Java 8, Ubuntu 16.04. 
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

I downloaded and unzipped it. After running `sh jes.sh`, the error prompted. Comparing to your requirement, openjdk 1.7 and fedora, I doubt those requirements could cause such an error.

**Comment by mjguzdial** [comment]
I'm not sure that JES can run in 1.8 yet.  I run in 1.6 on my Mac.  I don't know yet what's involved in getting JES/Jython to run on the most recent Java.

 - Mark

________________________________

**Comment by xiaoleihuang** [comment]
@mjguzdial 
I tested it on my Win8 PC. It worked. Java 8 is deployed in the system. I guess it might be system specific. Since you compiled the linux-version in fedora, and debian is somewhat different in fedora. I'll try to compile the source code in ubuntu.

**Comment by xiaoleihuang** [comment]
@mjguzdial 
This issue is solved by recompiled it under Ubuntu 16.04. 
By Entering `ant release`, it generates a new release zip file for linux.

**Comment by xiaoleihuang** [comment]
BTW, I guess it should be caused by System gap between fedora and debian.

**Comment by ishandutta2007** [comment]
I am on OS-X 1.13 (High Sierra), I am still getting the same error.

ishandutta2007@MacBook-Pro:~/Documents/Projects/jes$ `java -version`
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

ishandutta2007@MacBook-Pro:~/Documents/Projects/jes$ `ant release`
> Buildfile: /Users/ishandutta2007/Documents/Projects/jes/build.xml
> 
> .......
> .......
> BUILD SUCCESSFUL
> Total time: 2 minutes 42 seconds

ishandutta2007@MacBook-Pro:~/Documents/Projects/jes$` bash jes.sh `
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> usage: dirname path
> Error: Could not find or load main class JESstartup
